### ISSUE TITLE
Test single column CSV files

### ISSUE THREAD

**Issue by gjbex** [gjbex/worker-ng#22]

**Comment by stevenvdb** [comment]
There is indeed a problem with single-column CSV files because `csv.Sniffer()` (which is used to detect the formatting of the CSV file) does not always work correctly. Attached are two single-column CSV files which only differ by one single additional entry in the `long.csv` file compared to `short.csv`. When parsing them with the following code:
```
from worker.data_sources import DataSource

for fn in ['short.csv', 'long.csv']:
    csv_fn = [fn]
    results = [value for value in DataSource(csv_fn, 1024, None, 'slurm')]
    print(f'DataSource = {fn}')
    print(results)
```
the output is:
```
DataSource = short.csv
[{'a': '0.28612208677605033'}, {'a': '0.21252235792487184'}, {'a': '0.8335603397123424'}, {'a': '0.5418934662667619'}, {'a': '0.8428118963429092'}, {'a': '0.5424953932491723'}, {'a': '0.7872269791741723'}, {'a': '0.9980834014744989'}, {'a': '0.5880799435156168'}, {'a': '0.20366763555107992'}, {'a': '0.26909639934934293'}, {'a': '0.2570813854585121'}, {'a': '0.824888456427143'}, {'a': '0.7755562386803501'}, {'a': '0.6588853623891855'}, {'a': '0.7791449803486404'}, {'a': '0.8993441156867563'}, {'a': '0.8867427419776599'}, {'a': '0.6433300089174632'}, {'a': '0.8091023150683209'}, {'a': '0.3322925726190965'}]
DataSource = long.csv
[{'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}, {'a': '0'}]
```
What happens is that for `short.csv` no delimiter is detected and the code (correctly) falls back to `SingleColumnDataSource`. For `long.csv`, the sniffer incorrectly detects `.` as a delimiter, leading to incorrect parsing. 
[long.csv](https://github.com/gjbex/worker-ng/files/15350465/long.csv)
[short.csv](https://github.com/gjbex/worker-ng/files/15350466/short.csv)
